### ISSUE TITLE
[JOSE review] Example notebook

### ISSUE THREAD

**Issue by darribas** [martibosch/swisslandstats-geopy#10]
The binder button nicely takes you to a demo that works. However, it's not clear where that notebook lives or, particularly, that it's not part of the package. Given it's a relatively light file, I'd encourage to include it on the `examples` folder of the package, where the user might expect it to be.

Similarly, it might help to add to that notebook that `!make download_data` will probably not work on Windows.

[openjournals/joss-reviews#1511](https://github.com/openjournals/joss-reviews/issues/1511)

**Comment by martibosch** [comment]
Hello,

I have moved the notebook and Makefile (with a note concerning Make and windows in the first cell of the notebook) into the `examples` folder of this repository and updated the README (and the Binder badge) in [e61704d](https://github.com/martibosch/swisslandstats-geopy/commit/e61704dccb27865e54f63dbfc96e92638061d46f). I hope that this addresses the issue.

Martí

**Comment by darribas** [comment]
Yep! that's excellent! Closing...
