### ISSUE TITLE
Latest github release v0.1 does not match the latest pypi release v0.6.1 

### ISSUE THREAD

**Issue by weikang9009** [martibosch/swisslandstats-geopy#2]
[v0.6.1 is tagged but not released on github](https://github.com/martibosch/swisslandstats-geopy/releases) 

openjournals/joss-reviews#1511

**Comment by martibosch** [comment]
Hello,

I have manually added a release for the latest tag (v0.6.1), and I will do so for the following releases.

Martí

**Comment by weikang9009** [comment]
Thanks! Looks good.
