### ISSUE TITLE
Community guidelines

### ISSUE THREAD

**Issue by weikang9009** [martibosch/swisslandstats-geopy#5]
Please add community guidelines: clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

related to https://github.com/openjournals/joss-reviews/issues/1511

**Comment by martibosch** [comment]
A [contribution guide](https://github.com/martibosch/swisslandstats-geopy/blob/master/CONTRIBUTING.md) and a [github issue template](https://github.com/martibosch/swisslandstats-geopy/blob/master/.github/ISSUE_TEMPLATE.md) have been added in [acc24d5](https://github.com/martibosch/swisslandstats-geopy/commit/acc24d5e596582913ca40336fec38a2479d2c6e4)
