### ISSUE TITLE
update figures in README.md

### ISSUE THREAD

**Issue by weikang9009** [martibosch/swisslandstats-geopy#6]
[README.md](https://github.com/martibosch/swisslandstats-geopy/blob/master/README.md) figures need to be updated  (due to the change in the plotting methods https://github.com/martibosch/swisslandstats-geopy/issues/4)

related to https://github.com/openjournals/joss-reviews/issues/1511

**Comment by martibosch** [comment]
Done in  [cd5fb12](https://github.com/martibosch/swisslandstats-geopy/commit/cd5fb12c103e91d57d4c09d3e301270c6abf0aa3) :heavy_check_mark:
