### ISSUE TITLE
target audience

### ISSUE THREAD

**Issue by weikang9009** [martibosch/swisslandstats-geopy#7]
Could you explain who the target audience is in the documentation as well as in the paper? I 

https://github.com/openjournals/joss-reviews/issues/1511

**Comment by martibosch** [comment]
I have added (to the README, documentation and paper) the target audience and examples of its use in the literature in [e560582](https://github.com/martibosch/swisslandstats-geopy/commit/e560582a62ddc0f5f03589d32e19c7769c8a771c).

Martí
