### ISSUE TITLE
Reference DOI

### ISSUE THREAD

**Issue by weikang9009** [martibosch/swisslandstats-geopy#8]
try to update the references in the paper to fulfill the requirement:

References: Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

https://github.com/openjournals/joss-reviews/issues/1511

**Comment by martibosch** [comment]
Hello,
I hope that this is addressed in [6ac4b28](https://github.com/martibosch/swisslandstats-geopy/commit/6ac4b289ab7242a1f1b82a61f879ccaaab3ccf9a).

Martí
